In [103]:
# Ejercicio 17: Ecuacion de ondas
# utt = 4uxx

import numpy as np


def wave_equation(K, N, M, u0, u0t, uNt, h, k):
    """ 
    wave_equation: computa la solución a la ecuación de onda utt = K uxx 
    @param K: constante de onda
    @param N: numero de pasos en x
    @param M: numero de pasos en t
    @param u0: vector de N+1 valores con los valores de u(xi, 0)
    @param u0t: valor de u(0, t)
    @param uNt: valor de u(xN, t)
    @param h: paso en x
    @param k: paso en t
    Nota: asume ut(x, 0) = 0 y realiza una aproximacion de primer orden ui0 = ui1
    """
    # Matriz solucion
    u = np.zeros((N+1, M+1))
    u[:,0] = u0
    u[0] = u0t
    u[N] = uNt
    # ut(x,0) = 0 => ui0 = ui1
    u[:,1] = u[:,0]
    # ( a1 a2 a3 a4 ) ( uij     )  = v.T * u
    #                 ( ui(j-1) )
    #                 ( u(i+1)j )
    #                 ( u(i-1)j )
    v = [ 2 - 2*K*k**2/h**2, -1, 4*k**2/h**2, 4*k**2/h**2 ]
    for j in range(1, M):
        for i in range(1, N):
            prev = [ u[i,j], u[i,j-1], u[i+1,j], u[i-1,j] ]
            u[i,j+1] = np.inner(v, prev)
    
    return u

# Cte de la ecuacion de onda
K = 4
# Paso en x
h = 0.2
# Paso en t
k = 0.1
# Cantidad de pasos en x
N = 5
# Cantidad de pasos en t
M = 5

# Condiciones iniciales 
# u(x,0) = sen(pi x)
u0 = [np.sin(np.pi * xi) for xi in np.linspace(0, N*h, N + 1)]
# u(0,t) = u(1,t) = 0
u0t = 0
uNt = 0

u_ej17 = wave_equation(K, N, M, u0, u0t, uNt, h, k)
print(f'Matriz solucion:')
print(np.round(u_ej17,3))

t = np.linspace(0, M*k, M+1)
title = f'Solucion a la ecuacion de onda, K = {K}'
anim = Animator()
anim.plot_animation(t, u_ej17, title, 100)

Matriz solucion:
[[ 0.     0.     0.     0.     0.     0.   ]
 [ 0.588  0.588  0.363 -0.    -0.363 -0.588]
 [ 0.951  0.951  0.588  0.    -0.588 -0.951]
 [ 0.951  0.951  0.588 -0.    -0.588 -0.951]
 [ 0.588  0.588  0.363  0.    -0.363 -0.588]
 [ 0.     0.     0.     0.     0.     0.   ]]


In [102]:
""" Para mostrar la evolución en el tiempo de las soluciones """

from matplotlib import animation, rc
import matplotlib.pyplot as plt
from IPython.display import HTML

plt.rcParams['animation.html'] = 'jshtml'


class Animator:
    def __init__(self):
        self.fig, self.ax = plt.subplots()
        self.u_plot, = plt.plot([], [], color='r', LineWidth=2)     
    
    def plot_animation(self, t, u, title, interval):
        self.ax.set_title(title)
        self.t = t
        self.u = u
        anim = animation.FuncAnimation(self.fig, lambda iter: self._update(iter), init_func=lambda: self._init_animation(), frames=len(t), interval=interval)
        display(HTML(anim.to_jshtml()))
        plt.close()
    
    def _init_animation(self):
        self.ax.set_xlim(self.t[0], self.t[-1])
        self.ax.set_ylim( 1.1 * np.amin(self.u), 1.1 * np.amax(np.abs(self.u)))
        return self.u[:0]

    def _update(self, iter):
        self.u_plot.set_data(self.t, self.u[:,iter])
        return self.u_plot

In [105]:
# Ejercicio 18: Ecuacion de calor
# ut = 1/4 uxx

def heat_equation(C, r, N, M, u0, u0t, uNt):
    """ 
    heat_equation: computa la solución a la ecuación del calor ut = C * uxx 
    @param C: constante de la ecuación de calor
    @param r: constante de la grilla = k/h^2
    @param N: numero de pasos en x
    @param M: numero de pasos en t
    @param u0: vector de N+1 valores con los valores de u(xi, 0)
    @param u0t: valor de u(0, t)
    @param uNt: valor de u(xN, t)
    """
    # Matriz solucion
    u = np.zeros((N+1, M+1))
    u[:,0] = u0
    u[0] = u0t
    u[N] = uNt
    # ( a1 a2 a3 ) ( uij     )  = v.T * u
    #              ( u(i+1)j )
    #              ( u(i-1)j )
    v = [ 1 - 2*r*C, r*C, r*C ]
    for j in range(0, M):
        for i in range(1, N):
            prev = [ u[i,j], u[i+1,j], u[i-1,j] ]
            u[i,j+1] = np.inner(v, prev)
    return u

# Paso en x
h = 0.2
# Paso en t
k = 0.02
# Cantidad de pasos en x
N = 5
# Cantidad de pasos en t
M = 5
# Condiciones iniciales 
# u(x,0) = 1 - |2x - 1|
u0 = [ 1 - np.abs(2*xi - 1) for xi in np.linspace(0, N*h, N + 1)]
# u(0,t) = u(1,t) = 0
u0t = 0
uNt = 0
# Constante de la ecuacion de calor
C = 0.5
u_ej2 = heat_equation(C, k/h**2, N, M, u0, u0t, uNt)
print(np.round(u_ej2,3))

t_ej2 = np.linspace(0, M*k, M+1)
title_ej2 = f'Solucion a la ecuacion de calor, C = {C}'
anim_ej2 = Animator()
anim_ej2.plot_animation(t_ej2, u_ej2, title_ej2, 500)

[[0.    0.    0.    0.    0.    0.   ]
 [0.4   0.4   0.375 0.344 0.312 0.283]
 [0.8   0.7   0.625 0.562 0.508 0.459]
 [0.8   0.7   0.625 0.562 0.508 0.459]
 [0.4   0.4   0.375 0.344 0.312 0.283]
 [0.    0.    0.    0.    0.    0.   ]]


In [106]:
# Ejercicio 19: Ecuacion de calor
# ut = 1/4 uxx

# Paso en x
h = 1
# Paso en t
k = 1
# Cantidad de pasos en x
N = 2
# Cantidad de pasos en t
M = 2

# Condiciones iniciales 
# u(x,0) = x^2
u0 = [ xi**2 for xi in np.linspace(0, N*h, N + 1)]
# u(0,t) = 0
# u(2,t) = 4
u0t = 0
uNt = 4
# Constante de la ecuacion de calor
C = 1/4
u_ej3 = heat_equation(C, k/h**2, N, M, u0, u0t, uNt)
print(np.round(u_ej3,3))

t_ej3 = np.linspace(0, M*k, M+1)
title_ej3 = f'Solucion a la ecuacion de calor, C = {C}'
anim_ej3 = Animator()
anim_ej3.plot_animation(t_ej3, u_ej3, title_ej3, 500)

[[0.   0.   0.  ]
 [1.   1.5  1.75]
 [4.   4.   4.  ]]


In [107]:
# Ejercicio 22: Ecuacion de ondas
# utt = 4uxx

# Cte de la ecuacion de onda
K = 1/4
# Paso en x
h = 1
# Paso en t
k = 1
# Cantidad de pasos en x
N = 2
# Cantidad de pasos en t
M = 2

# Condiciones iniciales 
# u(x,0) = sen(pi x)
u0 = [np.sin(np.pi / 2 * xi) for xi in np.linspace(0, N*h, N + 1)]
# u(0,t) = u(2,t) = 0
u0t = 0
uNt = 0

u_ej22 = wave_equation(K, N, M, u0, u0t, uNt, h, k)

print(np.round(u_ej22,3))

t = np.linspace(0, M*k, M+1)
title = f'Solucion a la ecuacion de onda, K = {K}'
anim = Animator()
anim.plot_animation(t, u_ej22, title, 500)

[[0.  0.  0. ]
 [1.  1.  0.5]
 [0.  0.  0. ]]
