In [18]:
# Ejercicio 1: Cuadrados minimos con DSV
# Forma 1: solución como combinación lineal de autovectores vk

import numpy as np

A = np.asarray([ [1, 1], [-1, 1], [-1, 1], [1, 1] ])
U, s, Vt = np.linalg.svd(A, full_matrices=True)

print('U:\n', U)
print('Sigma:\n', s)
print('V:\n', Vt.T)

b = [16, 8, -8, -32]
x = np.zeros(len(s))
for k in range(len(s)):
    x += np.dot(U.T[k],b)/s[k] * Vt[k] 
print('\nSolucion: ', x)

U:
 [[-0.5 -0.5  0.1 -0.7]
 [ 0.5 -0.5 -0.7 -0.1]
 [ 0.5 -0.5  0.7  0.1]
 [-0.5 -0.5 -0.1  0.7]]
Sigma:
 [2. 2.]
V:
 [[-1. -0.]
 [-0. -1.]]

Solucion:  [-4. -4.]


In [19]:
# Forma 2: Usar matriz pseudo inversa

sigma_dagger = np.zeros(A.T.shape)
np.fill_diagonal(sigma_dagger, 1/s)

print('Sigma Dagger:\n', sigma_dagger)

A_dagger = Vt.T @ sigma_dagger @ U.T
x_alt = A_dagger @ b

print('Solucion con pseudo inversa: ', x_alt)

Sigma Dagger:
 [[0.5 0.  0.  0. ]
 [0.  0.5 0.  0. ]]
Solucion con pseudo inversa:  [-4. -4.]


In [3]:
# Ejercicio 4: EDO Heun 
# y' = cos(y + t)

from ode_methods import heun, print_result, richardson, wanted_step

def funcion_carga(tn, yn):
    return np.cos(tn + yn)

yo = 0
to = 0
ha = 0.1
n = 2
ya = heun(to, ha, n, funcion_carga, yo)
print_result('Heun', n, ya[1:], None)

n = 4
hb = 0.05
yb = heun(to, hb, n, funcion_carga, yo)
print_result('Heun', n, yb[1:], None)

c = richardson(ya[-1][0], ha, yb[-1][0], hb, 2)
print(f'C = {c}')
print('Item c: ', np.abs(c*0.1**2))
error = 1e-6
print('Item d: ', wanted_step(c,error,2))

Heun con 2 pasos
[[0.09900333]
 [0.19412721]]
 
Heun con 4 pasos
[[0.0498751 ]
 [0.09925404]
 [0.1476556 ]
 [0.19462678]]
 
C = -0.06660908151877215
Item c:  0.0006660908151877216
Item d:  0.0038746571280073253
